language: node_js
node_js:
  - "node"

script: yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  repo: andrcuns/andrcuns.github.io
  target_branch: master

branches:
  only:
    - master