language: node_js
node_js:
  - "node"

script:
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then yarn lint; fi
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  repo: andrcuns/andrcuns.github.io
  target_branch: master

branches:
  only:
    - master